spring:
  application:
    name: springbootdocker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.21.0.2:5433/students?createDatabaseIfNotExist=true
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect