version: '3.9'

services:
  backend:
    image: monirzaman/spring-boot-docker
    container_name: spring-boot-docker
    build:
      context: ./spring-boot-docker
    ports:
      - '9090:8080'
    depends_on:
      - database
    networks:
      - test-network

  frontend:
    image: monirzaman/angular-docker
    container_name: angular-docker
    build:
      context: ./docker-angular-with-backend
    ports:
      - '8001:80'
    depends_on:
      - backend
    networks:
      - test-network

  database:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=students
    ports:
      - '5433:5432'
    volumes:
      - ./db-data:/var/lib/postgres
    networks:
      - test-network

volumes:
  db-data:

#networks:
#  test-network:
#    driver: bridge

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#          ip_range: 172.28.1.0/24 // not needed now
          gateway: 172.28.1.1